spring:
  application:
    #nome aqui não pode ter caracteres tipo _ para que o Feign não se perca. O mesmo nome que está aqui é o que vai aparecer no eureka e é o mesmo que deve estar na anotação @FeignClient(name = "ms-cambio-service") do serviço que vai acessar esse aqui (para que seja possível encontrar o serviço no load balance
    name: ms-cambio-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: cambio_service
    user: root
    password: admin123

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #endereço do eureka