spring:
  application:
    #nome aqui não pode ter caracteres tipo _ para que o Feign não se perca. O mesmo nome que está aqui é o que vai aparecer no eureka e é o mesmo que deve estar na anotação @FeignClient(name = "ms-cambio-service") do serviço que vai acessar esse aqui (para que seja possível encontrar o serviço no load balance
    name: ms-cambio-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    url: jdbc:mysql://localhost:3306/cambio_service?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306
#    schemas: cambio_service
    user: root
    password: admin123

management:
  tracing:
    sampling: # definindo % das amostras
      probability: 1 #5% quando for pra produção
  #Para evitar o erro:
  #2025-05-28T18:14:48.603-03:00 WARN 1 --- [ms-cambio-service] [/api/v2/spans}}] [ ] z.r.i.AsyncReporter$BoundedAsyncReporter : Spans were dropped due to exceptions. All subsequent errors will be logged at FINE level.
  #2025-05-28T18:14:48.603-03:00 WARN 1 --- [ms-cambio-service] [/api/v2/spans}}] [ ] z.r.i.AsyncReporter$BoundedAsyncReporter : Dropped 2 spans due to ResourceAccessException(I/O error on POST request for "http://localhost:9411/api/v2/spans": Connect to http://localhost:9411⁠ [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused)
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411/}api/v2/spans

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #endereço do eureka

  #A configuração abaixo é para evitar o erro:
#  2025-05-16T01:08:05.866-03:00 ERROR 3928 --- [api-gateway] [ctor-http-nio-3] a.w.r.e.AbstractErrorWebExceptionHandler: [ 2cd29eb8-1 ]  500 Server Error for HTTP GET "/MS-CAMBIO-SERVICE/cambio-service/7.87/USD/BRL"
#
#  java.net.UnknownHostException: Failed to resolve 'Raphael-PC.mshome.net' [A(1), AAAA(28)] after 2 queries
#    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150) ~[netty-resolver-dns-4.1.119.Final.jar:4.1.119.Final]
#    Suppressed:
#      reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
#  Error has been observed at the following site(s):
#    *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
#      *__checkpoint ⇢ HTTP GET "/MS-CAMBIO-SERVICE/cambio-service/7.87/USD/BRL" [ExceptionHandlingWebHandler]
  #Essa configuração vai alterar o XML de configuração do eureka conforme a imagem ErroFaltaInstanceHostanmeMS.png.
  #Outra opção é gerar a configuração no arquivo C:\Windows\System32\drivers\etc\hosts apontando Raphael-PC.mshome.net para localhost
  instance:
#    hostname: localhost #Raphael-PC.mshome.net
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${HOSTNAME:localhost}:${server.port}

springdoc:
  show-actuator: true
  api-docs:
    path: /cambio-service/v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html